# NOTE: reference - https://github.com/open-webui/open-webui/blob/main/run-compose.sh
services:
  open-webui:
    build:
      context: .
      args:
        OLLAMA_BASE_URL: "/ollama"
      dockerfile: Dockerfile
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG-main}
    container_name: open-webui
    volumes:
      - open-webui:/app/backend/data
    ports:
      - ${OPEN_WEBUI_PORT-3000}:8080
    environment:
      # basic
      WEBUI_SECRET_KEY:
      WEBUI_AUTH: False
      # openai
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      # ollama
      OLLAMA_BASE_URL: http://localhost:11434
      # searxng
      ENABLE_RAG_WEB_SEARCH: True
      RAG_WEB_SEARCH_ENGINE: "searxng"
      RAG_WEB_SEARCH_RESULT_COUNT:
      RAG_WEB_SEARCH_CONCURRENT_REQUESTS: 5
      SEARXNG_QUERY_URL: "http://searxng:8081/search?q=<query>"
    network_mode: host
    extra_hosts:
      - host.docker.internal:host-gateway
    depends_on:
      - pipelines
      - searxng
    restart: always

  pipelines:
    image: ghcr.io/open-webui/pipelines:main
    container_name: pipelines
    ports:
      - 9099:9099
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - pipelines:/app/pipelines
    environment:
      PIPELINES_URLS: https://github.com/open-webui/pipelines/blob/main/examples/pipelines/providers/anthropic_manifold_pipeline.py
    restart: always

  searxng:
    image: searxng/searxng:latest
    container_name: searxng
    ports:
      - "8081:8080"
    volumes:
      - searxng:/etc/searxng
    restart: always

volumes:
  open-webui: {}
  pipelines: {}
  searxng: {}
